#!/bin/env sh

#getMoc() {
#	if [ -n "$(pgrep mocp)" ]; then
#		mocs=$(mocp --info | grep "State")
#		moci=$(mocp -Q"%artist %title")
#		if [ "$moci" = " " ]; then
#			moci="No title"
#		fi
#		echo -ne "\x06[ ♬ $mocs - $moci ]\x01"
#	else
#		echo -ne "[ ♬ Off ]"
#	fi
#}

scal='\uF073' #
svol='\uF357' #
sclk='\uF3D6' #
smai='\uF003' #
sdsk='\uFOAO' #
snet='\uF2F7' #
swif='\uF35C' #

getVol() {
	vol=$(amixer get Master | grep -E -o '[0-9]{1,3}?%' | head -1)
	echo -ne "\x0A$svol\x01$vol"
}

getDate() {
	dat=$(date +"%a, %d.%m.%y")
	clk=$(date +"%R")
	echo -ne "\x0A$scal\x01$dat\x0A$sclk\x01$clk"
}

while true; do
	xsetroot -name "$(getVol)$(getDate)                          "
	sleep 3s
done
