#!/usr/bin/bash
# vim:ts=4:sw=4:expandtab

## TODO:

echo '{ "version": 1 }['
echo '[]'

COL_DEF=#458588
COL_ACT=#e9dab2
COL_INA=#504945
COL_RED=#fe8019
COLORI3="$COL_DEF"

function Probel(){
    echo -ne '{"full_text":" "},'
}

function getMoc() {
    COLORI3="$COL_INA"
    local plstat=''
    local plsong='off'
    local icn=( "" "" "" "")
    local icn1=${icn[0]}
    if [ -n "$(pgrep mocp)" ]; then
        plstat=$(mocp --info | grep "State" | sed "s/State: //")
        case "$plstat" in
            "STOP")
                icn1=${icn[1]}
                ;;
            "PAUSE")
                icn1=${icn[2]}
                ;;
            "PLAY")
                icn1=${icn[3]}
                COLORI3="$COL_ACT"
                ;;
            *)
                icn1=${icn[0]}
        esac
        plsong=$(mocp -Q'%title')
        if [ "$plsong" = '' ]; then
            plsong=$(mocp -Q'%file')
        fi
    elif [ -n "$(pgrep cmus)" ]; then
        plstat=$(cmus-remote -Q | grep 'status' | sed "s/status //")
        case "$plstat" in
            "stopped")
                icn1=${icn[1]}
                ;;
            "paused")
                icn1=${icn[2]}
                ;;
            "playing")
                icn1=${icn[3]}
                COLORI3="$COL_ACT"
                ;;
            *)
                icn1=${icn[0]}
        esac
        plsong=$(cmus-remote -Q | grep "file" | sed "s/file //")
    fi
    echo -ne '{"full_text":"'$icn1 $plstat' - '$plsong'","color":"'$COLORI3'"},'
}

function getLang() {
    COLORI3="$COL_DEF"
    local lng=
    [ "`xset -q | awk -F \" \" '/Group 2/ {print($4)}'`" = "on" ] && lng="ru" && COLORI3="$COL_RED" || lng="en"
    echo -ne '{ "full_text":" '$lng'","color":"'$COLORI3'","border":"'$COLORI3'","border_top":0,"border_left":0,"border_right":0,"border_bottom":1 },'
}

function getVol() {
    COLORI3="$COL_DEF"
    local icn=( "" "" "" "🔇")
    local icn1=${icn[0]}
    [[ $(pamixer --get-mute) = "true" ]] && {
        local vol="mute"
        icn1=${icn[3]}
    } || {
            local vol="$(pamixer --get-volume)"
            [ "$vol" -lt 20 ] && COLORI3="$COL_INA"
            [[ "$vol" -lt 80 && "$vol" -ge 20 ]] && COLORI3="$COL_ACT" && icn1=${icn[1]}
            [ "$vol" -ge 80 ] && COLORI3="$COL_RED" && icn1=${icn[2]}
          }
    echo -ne '{ "full_text":"'$icn1 $vol'%","color":"'$COLORI3'","border":"'$COLORI3'","border_top":0,"border_left":0,"border_right":0,"border_bottom":1 },'
}

function getDay() {
    COLORI3="$COL_DEF"
    local day="$(date +'%a, %d %b')"
    [ "$(date +'%u')" -gt "5" ] && COLORI3="$COL_RED"
    echo -ne '{ "full_text":" '$day'","color":"'$COLORI3'","border":"'$COLORI3'","border_top":0,"border_left":0,"border_right":0,"border_bottom":1 },'
}

function getTme() {
    COLORI3="$COL_DEF"
    local tme="$(date +'%R')"
    [[ "$(date +'%H')" < "06" && "$(date +'%H')" > "21" ]] && COLORI3="$COL_ACT"
    echo -ne '{ "full_text":" '$tme'","color":"'$COLORI3'","border":"'$COLORI3'","border_top":0,"border_left":0,"border_right":0,"border_bottom":1 },'
}

function getNet() {
    local eth=$(cat /sys/class/net/e*/operstate)
    local wif=$(cat /sys/class/net/w*/operstate)
    local icn=( "" "" "" )
    local icn1=${icn[2]}
    COLORI3="$COL_INA"
    [[ "$eth" = "up" || "$wif" = "up" ]] && COLORI3="$COL_ACT"
    [ "$wif" = "up" ] && icn1=${icn[1]}
    [ "$eth" = "up" ] && icn1=${icn[0]}
    echo -ne '{ "full_text":"'$icn1'","color":"'$COLORI3'","border":"'$COLORI3'","border_top":0,"border_left":0,"border_right":0,"border_bottom":1 }'
}

while :;
do
    echo -e ',['$(Probel)$(getMoc)$(getLang)$(getVol)$(getDay)$(getTme)$(getNet)']'
    sleep 1
done
