#!/bin/sh -e

[ -x /usr/bin/i3lock ] && {
    file1=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
    file2=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
    # Take a screenshot
    import -window root "$file1"
    # Pixellate it 10x
    convert "$file1" -blur 0x3 "$file2"
    # Lock screen displaying this image.
    i3lock -i "$file2"
}
